---
title: "bateni_fisheries"
author: "MMB"
date: "7/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)  
library(janitor) 
library(paletteer) # install.packages("paletteer")
```

## 
```{r}
us_landings <- read_csv(here("data","noaa_landings.csv"),na = "no data")
summary(us_landings)
View(us_landings)
names(us_landings)
head(us_landings)
tail(us_landings)
```
## 
```{r}
salmon_clean <- us_landings %>% 
  clean_names()
names(salmon_clean)
```
##
```{r}
salmon_clean <- us_landings %>% 
  clean_names() %>% # Make column headers snake_case
  mutate(
    afs_name = str_to_lower(afs_name)
  ) %>% # Converts character columns to lowercase
  mutate(dollars_num = parse_number(dollars_usd)) %>% # Just keep numbers from $ column
  filter(str_detect(afs_name, pattern = "salmon")) %>% # Only keep entries w/"salmon"
  separate(afs_name, into = c("group", "subgroup"), sep = ", ") %>% # Note comma-space
  drop_na(dollars_num) # Drop (listwise deletion) any observations with NA for dollars_num
```
##
```{r}
salmon_us_annual <- salmon_clean %>% 
  group_by(year, subgroup) %>% 
  summarize(
    tot_value = sum(dollars_num, na.rm = TRUE),
  )
head(salmon_us_annual)
```
##
```{r}
salmon_gg <- 
  ggplot(salmon_us_annual, 
         aes(x = year, y = tot_value, group = subgroup)) +
  geom_line(aes(color = subgroup)) +
  theme_bw() +
  labs(x = "year", y = "US commercial salmon value (USD)") +
    scale_color_paletteer_d("colorblindr::OkabeIto")

salmon_gg
```
!()[https://octodex.github.com/images/blacktocats.png]



